### ISSUE TITLE
Error: No "exports" main defined

### ISSUE THREAD

**Issue by Paultje52** [discordjs/discord-api-types#213] opened 2021-10-02 14:44 UTC
**Please describe the problem you are having in as much detail as possible:**
When trying to use `discord-api-types` with TypeScript, I'm getting the following error.
```
Error: No "exports" main defined in C:\Users\Paul\Desktop\test\node_modules\discord-api-types\package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:413:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:652:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\Users\Paul\Desktop\test\test.ts:1:1)
```

I tried it first with other code in a project, then a separate file and then a clean project, with a clean install, but the error doesn't change. I'm sure it's not me.

**Include a reproducible code sample here, if possible:**
- Create a new project (folder)
- Run `npm i -s discord-api-types`
- Create a file called `test.ts` with the following code. 
```ts
import { Routes } from "discord-api-types";

console.log(Routes.applicationCommands("123"));
```
- Run `ts-node test` and see the error.

**Further details:**

- Runtime:
  - Node.js version: v16.7.0

**Comment by Megatank58** [comment] 2021-10-02 14:50
Exports are versioned by their api version numbers so for example to import version 9
```js
import { Routes } from "discord-api-types/v9"
```

**Comment by Paultje52** [comment] 2021-10-02 14:53
Why doesn't typescript give me an error then? I thought that the whole point of using typescript was to prevent issues like these.

**Comment by ImRodry** [comment] 2021-10-02 16:00
I think this is caused by these lines on package.json
![image](https://user-images.githubusercontent.com/38259440/135723882-39d91596-3c8f-4904-8f22-08e44739f9b2.png)
Since TypeScript sees there is a main file, it thinks that that is the file that gets exported when you import the module. I think this can be easily fixed by removing these 3 lines from package.json, but I'm not entirely sure.

**Comment by vladfrangu** [comment] 2021-10-02 16:04
Could remove them or wait for TS to support exports. Those fields are there for snowpack more than anything, but I think I can remove that now since we have deno.land available

**Comment by ImRodry** [comment] 2021-10-02 16:06
Why not export v9 by default though?

**Comment by vladfrangu** [comment] 2021-10-02 23:57
Because, for example, when v10 comes, changing the export directly could break things if there's major changes, while this forces you to keep your code up to date with whatever version of the API you're using

**Comment by ImRodry** [comment] 2021-10-03 00:25
Yeah fair enough I guess
The only issue with deleting the types line is that the error that would generate wouldn’t be too explicit and it would just tell you it can’t find the type declarations, and users would still have to figure out that they need to select the version by themselves so I’m not sure that’s the best way to go here

**Comment by Paultje52** [comment] 2021-10-03 16:27
Another solution could be to throw an error when importing `discord-api-types` without specifying the version

**Comment by ImRodry** [comment] 2021-10-03 16:28
> Another solution could be to throw an error when importing `discord-api-types` without specifying the version

Before runtime the only possible error afaik is the no types error. On runtime an error is already thrown which is literally the topic of this issue

**Comment by vladfrangu** [comment] 2021-12-24 15:39
This is probably fixed in 0.26.0. Can you verify?

**Comment by nhcarrigan** [comment] 2022-01-28 21:35
Hello! I can confirm I just ran in to this same issue on `0.26.1`.

**Comment by vladfrangu** [comment] 2022-01-28 21:37
Hmm.. It seems that I forgot to remove `types` from the package.json, maybe that's the issue? I think best bet is to wait for TS to implement the nodejsnext target

**Comment by vladfrangu** [comment] 2022-03-05 18:33
So:

1. `types` property has been removed a while ago.
2. If you're one of the 5 people actually using `NodeNext` module/moduleResolution, next release will have proper support for it.

I don't think this is an issue anymore, so I will be closing this. Please followup if you notice any wacky behavior related to this

**Closed by vladfrangu** 2022-03-05 18:33 UTC
Labels: bug
