### ISSUE TITLE
Type of permissions slash commands

### ISSUE THREAD

**Issue by mqtdv** [discordjs/discord-api-types#441] opened 2022-05-24 17:32 UTC
- My issue is to propose to remove the type of permissions related to slash commands which for some are no longer used because of the new Discord API.

**Comment by vladfrangu** [comment] 2022-05-25 18:49
?? I'm not sure I follow..can you share what types you're referring to?

**Comment by robert-koch** [comment] 2022-05-30 18:10
I'm not sure if this is the same issue that @MathisAudureau is referencing, but something did seem to break with the typings between 0.33.0 and 0.33.1.

The type returned by the `toJSON()` function on a `SlashCommandBuilder` object is now throwing an error.

This is easily reproducible by creating a brand new, empty Typescript project, installing the `@discordjs/builders` and `discord-api-types`:

```json
"dependencies": {
    "@discordjs/builders": "^0.13.0",
    "discord-api-types": "^0.33.1"
}
```

After those to libraries are installed, create a new `.ts` file and add the following:

```typescript
import { RESTPostAPIApplicationCommandsJSONBody } from "discord-api-types/v10";
import { SlashCommandBuilder } from "@discordjs/builders";

const testSlashCommand: RESTPostAPIApplicationCommandsJSONBody =
  new SlashCommandBuilder()
    .setName("test")
    .setDescription("This is a test command.")
    .toJSON();
```

In 0.33.0, this compiles fine, but in 0.33.1, the `testSlashCommand` throws the following error:

```
type 'import("/path/to/node_modules/@discordjs/builders/node_modules/discord-api-types/rest/v10/interactions").RESTPostAPIApplicationCommandsJSONBody' is not assignable to type 'import("/path/to/node_modules/discord-api-types/rest/v10/interactions").RESTPostAPIApplicationCommandsJSONBody'.
Type 'RESTPostAPIChatInputApplicationCommandsJSONBody' is not assignable to type 'RESTPostAPIApplicationCommandsJSONBody'.
Type 'import("/path/to/node_modules/@discordjs/builders/node_modules/discord-api-types/rest/v10/interactions").RESTPostAPIChatInputApplicationCommandsJSONBody' is not assignable to type 'import("/path/to/node_modules/discord-api-types/rest/v10/interactions").RESTPostAPIChatInputApplicationCommandsJSONBody'.
Property 'default_member_permissions' is missing in type 'RESTPostAPIChatInputApplicationCommandsJSONBody' but required in type 'AddUndefinedToPossiblyUndefinedPropertiesOfInterface<Omit<APIApplicationCommand, "id" | "application_id" | "description" | "type" | "version" | "guild_id" | "name_localized" | "description_localized">>'.
```

This was causing me issues, so I needed to revert back to 0.33.0 to be able to continue using the slash commands builder.

Thanks,

Rob

**Comment by davidkhierl** [comment] 2022-05-30 20:48
can confirm this typing issue happens in 0.33.1, had to revert back to 0.33.0

**Comment by vladfrangu** [comment] 2022-05-30 20:51
Thats because of version mismatches between /builders and /types, which is sadly to be expected 😓

**Comment by vladfrangu** [comment] 2022-05-30 23:26
@davidkhierl @robert-koch https://github.com/discordjs/discord-api-types/pull/460 has solved the issue. Once the release is out, please reinstall deps and it should work again

**Comment by vladfrangu** [comment] 2022-06-27 20:12
I'm going to be closing this as I'm still not sure what the original author means by this issue, and the other alternative issues mentioned have been fixed.

Feel free to followup with an explanation and we'll reopen this

**Closed as completed by vladfrangu** 2022-06-27 20:12 UTC
